// settings.js contains all the settings for the game.

// GAME TEMPO
const GAME_TEMPO = 1;

// COLORS
const COLOR_INDICATOR_SUCCESS = 0x00ff00;
const COLOR_INDICATOR_FAIL = 0xff0000;
const COLOR_INDICATOR_NEUTRAL = 0x999999;

const COLOR_PLANET_NEUTRAL = 0x999999;

const COLOR_CONNECTION = 0x090909;

const COLORS_PLAYERS = [0xe65100, 0xdfdf00, 0x00e626, 0xe002ca, 0x02cde0];
// SYSTEM CREATION
const CONNECT_ALL_PLANETS = false;
const INPUT_SYSTEM_JSON = "sys1.json";

const PLAYERS_AMOUNT = 3;
const BOTS_ONLY = false;

// GAME MECHANICS
const PLANET_RANDOM_BREEDING_INFLUENCE = 0.5;
const PLANET_OCCUPIED_BREEDRATE = 1;
const PLANET_NEUTRAL_BREEDRATE = 0.3;

const PLANET_INIT_POPULATION = 100;
const PLANET_NEUTRAL_INIT_POPULATION_MULTIPLIER = 0.3;

const PLANET_ATTACK_SPEED = 10;
const PLANET_ATTACK_SPEED_BY_RADIUS_INFLUENCE = 0.5;

const SHIP_INIT_SPEED = 80;
const SHIP_ACC = 200;

export {
  GAME_TEMPO,
  COLOR_INDICATOR_SUCCESS,
  COLOR_INDICATOR_FAIL,
  COLOR_INDICATOR_NEUTRAL,
  COLOR_PLANET_NEUTRAL,
  COLOR_CONNECTION,
  COLORS_PLAYERS,
  CONNECT_ALL_PLANETS,
  INPUT_SYSTEM_JSON,
  PLAYERS_AMOUNT,
  BOTS_ONLY,
  PLANET_RANDOM_BREEDING_INFLUENCE,
  PLANET_OCCUPIED_BREEDRATE,
  PLANET_NEUTRAL_BREEDRATE,
  PLANET_INIT_POPULATION,
  PLANET_NEUTRAL_INIT_POPULATION_MULTIPLIER,
  PLANET_ATTACK_SPEED,
  PLANET_ATTACK_SPEED_BY_RADIUS_INFLUENCE,
  SHIP_INIT_SPEED,
  SHIP_ACC,
};
