// settings.js contains all the settings for the game.

// COLORS
const COLOR_INDICATOR_SUCCESS = 0x00ff00;
const COLOR_INDICATOR_FAIL = 0xff0000;
const COLOR_INDICATOR_NEUTRAL = 0x999999;

const COLOR_PLANET_NEUTRAL = 0x999999;

const COLOR_CONNECTION = 0x090909;

const COLORS_PLAYERS = [0xdfdf00, 0x00e626, 0xe65100, 0xe002ca, 0x02cde0];
// OTHER
const CONNECT_ALL_PLANETS = false;
const INPUT_SYSTEM_JSON = "sys1.json";
const PLAYERS_AMOUNT = 3;

export {
  COLOR_INDICATOR_SUCCESS,
  COLOR_INDICATOR_FAIL,
  COLOR_INDICATOR_NEUTRAL,
  COLOR_PLANET_NEUTRAL,
  COLOR_CONNECTION,
  COLORS_PLAYERS,
  CONNECT_ALL_PLANETS,
  INPUT_SYSTEM_JSON,
  PLAYERS_AMOUNT,
};
